#! /bin/sh
sleep 1
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -c &

# Bar
sh $HOME/.config/polybar/start.sh

# Wallpaper
hsetroot -center $HOME/Pictures/wallpaper.jpg 

# Mouse
xsetroot -cursor_name left_ptr

bspc config focused_border_color "#ffffff"
#bspc config focused_border_color "#1CFFD2"
bspc config border_width         2
bspc config window_gap           0 #12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 40
bspc config bottom_padding 10

bspc monitor -d I II III IV V
bspc monitor HDMI-1  -d IV V VI 

