#! /bin/sh
sleep 1
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -c &

# Bar
sh $HOME/.config/polybar/start.sh

# Wallpaper
hsetroot -center $HOME/Pictures/wallpaper.jpg 

# Mouse
xsetroot -cursor_name left_ptr

bspc config focused_border_color "#26ff72"
#bspc config focused_border_color "#1CFFD2"
bspc config border_width         2
bspc config window_gap           0 #12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# idk
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 30
bspc config bottom_padding 0

bspc monitor -d I II III IV V
bspc monitor HDMI-2  -d VI VII VIII IX 

