#! /bin/sh

sleep 1
pgrep -x sxhkd > /dev/null || sxhkd &

sh /home/mattia/.config/polybar/start.sh

hsetroot -cover /home/mattia/Immagini/wallpaper.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          7

bspc config  top_padding        35
bspc config focused_border_color "#1CFFD2"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
