# Set colors
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

# Change prefix key
set -g prefix C-t
unbind C-b

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Enable mouse support
set -g mouse on

# Start from 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Plugins
set -g @tpm_plugins '             \
  tmux-plugins/tpm                \
  tmux-plugins/tmux-sensible      \
  tmux-plugins/tmux-yank          \
  christoomey/vim-tmux-navigator  \
'

# status line
set -g status-justify left
set -g status-style "bg=terminal,fg=color10"
set -g status-interval 2

# window status
set-option -g status-position bottom
setw -g window-status-format " #[bg=color4,fg=color0,noreverse]▓░ #I:#W "
setw -g window-status-current-format " #[bg=color10,fg=color0,noreverse]▓░ #I:#W "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
