# Hypridle Configuration

general {
    # after_sleep_cmd = swaymsg output * dpms on
    ignore_dbus_inhibit = false
    lock_cmd = hyprlock
}

# Lock screen after 10 minutes of inactivity
listener {
    timeout = 600  # 10 minutes in seconds
    on-timeout = hyprlock
}

# Turn off displays after 15 minutes (optional)
listener {
    timeout = 900  # 15 minutes in seconds
    # on-timeout = hyprctl dispatch dpms off
    # on-resume = hyprctl dispatch dpms on
}
